# @package _global_

dataset_name: megan

dataset:
  name: zjumocap
  root_dir: "data/data_prepared"
  subject: megan
  refine: false

  train_views: [ '00' ]
  val_views: ['01', '02', '03', '04', '05', '06', '07', '08', '09']
  test_views:
    view: ${dataset.val_views}
    video: ['09']
    all: []
  predict_views: ['01']

  train_frames: [ 0, 0, 1 ]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 0, 1]
    video: [0, 0, 1]
    all: [0, 0, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
  disable_filter3D: false